### ISSUE TITLE
Windows 没有正常工作

### ISSUE THREAD

**Issue by haiya6** [sxzz/unplugin-glob#1]
### Describe the bug

/

### Reproduction

https://github.com/haiya6/unplugin-glob-issue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 7.75 GB / 15.82 GB
  Binaries:
    Node: 16.14.2 - d:\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - d:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by haiya6** [comment]
https://github.com/sxzz/unplugin-glob/blob/9522cf5795aafcbf0c69493fc98505567bfbff6f/src/index.ts#L33

也许是这里的 `id` 包含了 Windows 的磁盘路径导致，磁盘路径中有 `:`，如 `D:/p/filename.ts`

**Comment by sxzz** [comment]
已知问题，目前暂无 Windows 机器调试
