### ISSUE TITLE
Feature request: Can support convert `default exports` to `named exports`?

### ISSUE THREAD

**Issue by penjj** [sxzz/unplugin-glob#48]
https://github.com/sxzz/unplugin-glob/blob/f48b16ace91ef566a67d7e6a7f24a221ed513d79/src/index.ts#L51

Like vue barrel file, that's is very useful.

```ts
export { default as MyCard } from './card.vue'
export { default as MyButton } from './button.vue'
```

**Comment by sxzz** [comment]
Maybe you need https://github.com/unplugin/unplugin-vue-named-export
